enable_audio_bell no

include color.ini

font_family	HackNerdFont
font_size 13

disable_ligatures never

url_color #61afef

url_style curly

map ctrl+left neighboring_window left
map ctrl+right neighboring_window right
map ctrl+down neighboring_window down
map ctrl+up neighboring_window up

shell zsh
